### PR TITLE
Fixing cmake, #230

### LINKED ISSUE #230: [Request] CMake
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| CMake   | `CMakeSetup` | Application |cmakesetup|

### Desktop file

```
[Desktop Entry]
Version=1.0
Name=CMake
Comment=Cross-platform buildsystem
Exec=cmake-gui %f
Icon=CMakeSetup
Terminal=false
X-MultipleArgs=false
Type=Application
Categories=Development;
StartupNotify=true
MimeType=application/x-cmakecache;

```

Another Developer tool icon request.

### PR DESCRIPTION
**Pull request by now-im**
The icon name was wrong, so I created a symbolic link with correct icon name. 
fixes #230

### CODE REVIEW

**Comment by Riotism** [comment]
@now-im unrelated to this PR, but you should not push commits using your master branch. It's why so many unrelated commits are listed here.

**Comment by now-im** [comment]
@Riotism I tried with the branch but no idea why this pull request is shown here. Most of them have been merged.

**Comment by now-im** [comment]
@keeferrourke you can also add the latest commit. These are system link that can work for these icons. From now on I will use cherry-branch.

**Comment by keeferrourke** [comment]
@now-im this PR is identical to #296 and has the same issues. Please only submit patches to files that directly pertain to the PR at hand.

I'm going to close this for now. Feel free to open a new PR later.

**Pull request closed without merging**
