### PR TITLE
Update rstudio.svg

### PR DESCRIPTION
**Pull request by Riotism**
### Updated rstudio to address #259

| Icon name     | Old Icon     | New Icon     |
| :------------ | ------------ | ------------ |
| `rstudio.svg` | old | rstudio svg |

### CODE REVIEW

**Comment by now-im** [comment]
Much better.

**Comment by Riotism** [comment]
A lot of old icons do not fit the size specifications for the icon template in the Wiki. Is it intentional or are we moving towards standardizing them to the template?

**Comment by keeferrourke** [comment]
@Riotism in process of moving towards standardizing the icons to fit the template specified in the wiki; there are just a lot of them to be resized :)

**Comment by Riotism** [comment]
I have resized the icon to 44x44. I left the border at 2px because the template has a border of 1.8333px for some reason and it makes the SVG rendering blurry. I also don't really like svgcleaner because it leaves some messy code and doesn't clean out unnecessary Inkscape transforms. I already hand-edit my SVGs so the filesize shouldn't be too large.

**Comment by now-im** [comment]
@Riotism  Could you tell me how you do it by hand? Which codes do you omit? I also don't like svgcleaner. It tends to break things.

**Comment by Riotism** [comment]
@now-im I hand-edit SVGs using a text editor. After I use Inkscape to create what I want an icon to look like, I use Inkscape's XML editor to remove all `transform`. Then I use the Transform tool (Ctrl+Alt+M) to move everything back to place. I save it as a plain SVG (not "Inkscape SVG"). Then I remove the following using a text editor:
- `<metadata>` and everything in it
- `viewBox` in `<svg>` (viewBox shouldn't be needed for icons)
- unneeded `id` attributes in `defs`, `stop`, `path`, `circ`, `rect`, etc.
- unneeded `stroke-opacity`, `stroke`, `fill-opacity`, `stroke-linecap`, `stroke-linejoin`, `stroke-miterlimit`, `stroke-dasharray`, etc.
- unneeded `<g>`

Then I change:
- All `#XXYYZZ` to `#XYZ`
- CSS `style` attributes to XML attributes (example: `style="fill:#FF0"` to `fill="#FF0"`)

This should remove most Inkscape junk without losing the document structure.

**Comment by now-im** [comment]
Thanks a lot for writing it down. I will be saving it. I am still quite a newbie at this but this will greatly help. Open source is truly beautiful. One stranger helping another with any expectation of benefit. Thanks again.

**Pull request merged**
