### PR TITLE
Add 'Visual Studio Code' icon

### PR DESCRIPTION
**Pull request by davidpob99**
Added  `vscode.svg`

vscode

### CODE REVIEW

**Comment by keeferrourke** [comment]
This icon is not in line with the (admittedly undocumented) design guidelines. IDEs and similar applications should look like [builder](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/builder.svg) or [eclipse](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/eclipse.svg) or [IntelliJ](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/intellij.svg), etc.

**Comment by davidpob99** [comment]
I have updated the icon and this is the result:
vscode

**Comment by keeferrourke** [comment]
@davidpob99 thanks for contributing!

**Comment by sathishkumar294** [comment]
Good work. @davidpob99

**Pull request merged**
