### PR TITLE
Fixing #189 & #190

### PR DESCRIPTION
**Pull request by now-im**

### CODE REVIEW

**Comment by now-im** [comment]
Sorry my bad. Just see the two file changed.

**Comment by keeferrourke** [comment]
image

What is the PR supposed to accomplish? Sorry... I'm confused here. You've only renamed files. Closing for now until this is fixed.

**Comment by now-im** [comment]
See the issues I have tagged. They were using the native icon provided by qt, as They were not correctly renamed according to their .desktop icon name. After renaming them used the icon .svg you created. I will provide screenshot after I reach home.

**Comment by now-im** [comment]
This is before file renaming:
screenshot_20180110_190806
This is after file renaming:
screenshot_20180110_184350
I made a mistake that I should have changed `qtdbusdesigner.svg` to `Qtproject-designer.svg`, but as they are identical icon, it should not be a problem.
You should really install a KDE distro in a small hard disk partition, other wise this kind of simple thing will miss out.

**Comment by keeferrourke** [comment]
Rather than renaming icons, which runs the risk of breaking support on other systems, you should create symbolic links instead. If you can do this, I'll merge the PR.

This said, I appreciate the effort you've made to improve the coverage of this iconset; particularly since my school/work/personal lives have been so ridiculously busy lately.

**Comment by now-im** [comment]
I am not getting much time either. My master is going on otherwise I would try to create some icon n my own. I will systemlink them with the `qt.svg`.

**Comment by now-im** [comment]
I have created systemlinks.

**Pull request closed without merging**
