### PR TITLE
Add: Meson

### PR DESCRIPTION
**Pull request by LinArcX**
### Description
Hi. 
Related to this issue:
https://github.com/keeferrourke/la-capitaine-icon-theme/issues/456

### CODE REVIEW

**Comment by keeferrourke** [comment]
Hey @LinArcX can you update the README with relevant information for how to use the meson build system for La Capitaine? I'll admit to not being familiar with build systems other than make or gradle.

**Comment by LinArcX** [comment]
@keeferrourke Done!
Consider updateing `version`, each time you update your repo.

**Comment by keeferrourke** [comment]
> Consider updateing version, each time you update your repo.

I have plans to change this repo so it makes better use of branching and versioning, since it honestly pains me right now -- I just haven't had much time to maintain this project as much as I'd like to. :)

**Comment by LinArcX** [comment]
Yes. you are right.
If you need help, inform me :)

**Comment by keeferrourke** [comment]
Hey @LinArcX is there a reason you closed this PR?

**Comment by LinArcX** [comment]
Hi. I think you don't need it anymore. Reopen?

**Comment by keeferrourke** [comment]
Hm, I'll ping you in a couple weeks when my exams finish and I've restructured this repository. I may need your help with `meson` then :) Cheers!

**Comment by LinArcX** [comment]
Sure. Good luck. :)

**Pull request closed without merging**
