### PR TITLE
Adding v4l-utils 

### LINKED ISSUE #192: [Request] v4l-utils
### Application information

| Application name | Icon name  | Context     | Icon reference |
| ---------------- | :--------- | :---------- | :------------- |
| v4l-utils   | `qv4l2.desktop` | Application | qv4l2   |

### Desktop file

```
[Desktop Entry]
Name=Qt V4L2 test Utility
Name[pt]=Utilitário de teste V4L2
Comment=Allow testing Video4Linux devices
Comment[pt]=Permite testar dispositivos Video4Linux
Exec=qv4l2
Icon=qv4l2
Terminal=false
Type=Application
Categories=AudioVideo;
Keywords=video;grabber;V4L;

```

Another minor developer tool icon request.

### PR DESCRIPTION
**Pull request by now-im**
fixes #192

### CODE REVIEW

**Comment by keeferrourke** [comment]
The v4l-utils icon has the wrong size/padding. The svg should be 48x48px (which is correct), but the image itself should be max 44x44px with a 2px border on all sides, as per the template in the wiki.

If you can fix this, I'll merge the PR.

**Comment by now-im** [comment]
Okay, this was my first attempt to create something. I will try again when I am at home. For now, in vacation now.

**Comment by now-im** [comment]
checkout the last commit. See if this works.

**Comment by now-im** [comment]
Last commit is the final icon.

**Comment by keeferrourke** [comment]
Same issue with #306... But I will merge this. Any future PRs may only have commits and files relevant to the request, or they will have to be closed.

**Comment by now-im** [comment]
No problem.  I have fixed the issue.

**Pull request merged**
