### PR TITLE
Add Mathematica mimetype

### PR DESCRIPTION
**Pull request by s1-ranjan**
### Description
I have added mimetype icon for mathematica, please have a look.

### CODE REVIEW

**Comment by keeferrourke** [comment]
Please remove the non-mimetype files from this PR. Additionally, note that the text on mimetype icons should be a Roboto 9, converted to paths from text. The recently added [go-src](https://github.com/keeferrourke/la-capitaine-icon-theme/commit/a40f0ed054f8868589d0e01da602017845ff4141?short_path=a4eac77#diff-a4eac770c2e7765b0bfbd047b4b48cf7) mimetype icon is a good example.

**Comment by keeferrourke** [comment]
Once these changes are made, I will be happy to merge this! :)

**Comment by s1-ranjan** [comment]
Can you please explain the term Roboto 9, as I looked in my package manager there is no such fonts, I am enclosing a screenshot 
Screenshot_2019-10-28_02-08-25
Screenshot_2019-10-28_02-08-10
So can you please suggest which fonts will fits best.

**Comment by keeferrourke** [comment]
Roboto font, size 9

**Comment by s1-ranjan** [comment]
Can you please have a look in my files and I have make the recommended changes, if it requires more improvement then please comment.

**Comment by keeferrourke** [comment]
@s1-ranjan looks like there are thousands of deleted files in this branch? Can you undo those deletions? I can't merge this as is, or even easily review the changes.

**Comment by s1-ranjan** [comment]
Please have a look, I have undo those deleations

**Comment by keeferrourke** [comment]
There are still a ton of new icons which aren't related to Mathematica, and over 80000 lines of deletions.

Can you please clean up this PR to _only_ include the new Mathematica icons? Other new icons should go into their own PRs.

**Comment by s1-ranjan** [comment]
I am closing my this request and I am creating a new request of pull from my new new repository please have a look over there.

**Pull request closed without merging**
