### PR TITLE
Add React JSX mimetype

### PR DESCRIPTION
**Pull request by r3b311i0n**
### Added mimetype for JavaScript XML

jsx

### CODE REVIEW

**Comment by Riotism** [comment]
The font doesn't look right.

**Comment by r3b311i0n** [comment]
Is it the size? The font is Roboto.

**Comment by keeferrourke** [comment]
Take a look at the mimetype for the *.deb files. Mimetypes should be based on that, though this is admittedly undocumented, and there are probably inconsistencies across files.

**Comment by r3b311i0n** [comment]
@keeferrourke do you mean vendor specific strings? I.e.

`application/vnd.debian.binary-package`

**Comment by Riotism** [comment]
The font type seems to be different from the one used for *.deb files (see `deb.svg`). @keeferrourke which font did you use to design those?

**Comment by r3b311i0n** [comment]
@Riotism I actually took the "javascript" label from the existing SVG for JavaScript (Roboto was used for the "JSX"). And you're right, it does look different from the *.deb files.

**Comment by keeferrourke** [comment]
The font inconsistency is definitely my fault. It doesn't look like I've been consistent at all. Lack of design documentation biting me in the ass here... I don't have a record of what fonts should be used. There is now officially a (WIP) [design document](https://github.com/keeferrourke/la-capitaine-icon-theme/wiki/Design-Guidelines).

The deb mimetype looks like it uses something similar to Product Sans (?), which if that is the case, it falls under a proprietary license and needs to be changed immediately.

This is... likely legacy stuff from the old (abandoned) project that this theme was forked from. I've opened a new issue at #316 for font inconsistencies. Let's just make Roboto the official font, since its inline with Material guidelines, is freely licensed, and installed on nearly every Linux system anyway.

**Pull request merged**
