### PR TITLE
Passwordsafe

### PR DESCRIPTION
**Pull request by stefano-b**
Proposal for Passwordsafe #454

### CODE REVIEW

**Comment by keeferrourke** [comment]
The legend on this icon look a _lot_ like the 1Password logo. Is this allowed to be used under a free license for a software that isn't 1Password?

**Comment by keeferrourke** [comment]
Hmm I guess Gnome PasswordSafe's icon just looks really similar. I suppose this is okay to merge.

**Comment by keeferrourke** [comment]
I'd be tempted to keep the "sheild" shape used by the icons for other password managers though.

**Comment by stefano-b** [comment]
I was genuinely unaware of the 1password icon, if you want I can try to modify it.

And when I designed this I had not considered to reuse the same icon from other similar password managers and only watched the original app icon; but reusing the existent icon for password managers is reasonable and consistent, feel free to choose the best solution :)

**Pull request merged**
