### PR TITLE
Cleaning metadata using the latest svgcleaner

### PR DESCRIPTION
**Pull request by now-im**
The latest update has some trick up its sleeve to reduce some more metadata. Previewing fine for me in gnome.

### CODE REVIEW

**Comment by Riotism** [comment]
I get that there's a need to reduce size, but collapsing everything into a single line makes it difficult for me to maintain each icon especially since I use a plain text editor to make my SVGs.

**Comment by keeferrourke** [comment]
I think I may adjust my stance on mandatory SVG cleaner use. Maintainability should be more important than size reduction.

This said, there are auto-formatters that should be able to expand the SVG source as required. The unix utility `tidy` comes to mind for this; it's a XML auto-formatter and can be installed by:

```
sudo apt-get install tidy    # debian/ubuntu
sudo dnf install tidy        # fedora/rhel
```
I'll close this for now, and will explore options for reducing size and maintaining readability in the near future. Keep an eye on the wiki; I'll post guidelines there once my work-load settles.

**Comment by now-im** [comment]
A proper wiki really helps newbs.

**Comment by keeferrourke** [comment]
@now-im, we're working on this.

**Pull request closed without merging**
