### PR TITLE
Added postman.svg (#218)

### PR DESCRIPTION
**Pull request by jojo243**
### New postman icon

I created a new postman icon (`apps/scalable/postman`) in La Capitaine-style.

postman

### CODE REVIEW

**Comment by keeferrourke** [comment]
Postman is an IDE of sorts? It may be better if you based your design off of [`builder.svg](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/builder.svg)

**Comment by LvLs9** [comment]
As for me, it is OK, only need to **add a triangle** in the bottom right corner and **more colorful palette**.

*For example, JetBrains environments:*

image

**Comment by keeferrourke** [comment]
@LvLs9 is correct

**Comment by jojo243** [comment]
New suggestion:

postman

**Pull request merged**
