### PR TITLE
Improving qtv4 utils

### PR DESCRIPTION
**Pull request by now-im**
I swear this is the last of this.

### CODE REVIEW

**Comment by now-im** [comment]
just merge the last commit.

**Comment by Riotism** [comment]
Hi, can you change the icon so that it's 44x44 with a 2px border?

**Comment by Riotism** [comment]
And also just a design suggestion (take it or leave it): to keep icons simple, I suggest that there be only one element (either the YouTube icon or the gear icon). To merge both, I'm thinking of a design where there's a gear at the center of the icon, with the "hole" in the gear replaced by the play triangle shape.

**Comment by now-im** [comment]
I need to be sure of something like the icon should be 44x44 including the border or excluding it?

**Comment by Riotism** [comment]
Including the border.

**Pull request closed without merging**
