### PR TITLE
Added icon for PulseEffects

### PR DESCRIPTION
**Pull request by zencubic**
### Description
Added an icon for PulseEffects

Preview:
pulseeffects

### CODE REVIEW

**Comment by keeferrourke** [comment]
I really don't like that colour palette, though I see that you grabbed it from the original icon.
If you can modify the palette to use brighter green gradients, I would probably accept this icon.

**Comment by zencubic** [comment]
Is this better?
pulseeffects svg

**Comment by LvLs9** [comment]
I like this. :+1:

**Comment by keeferrourke** [comment]
Definitely better. Should be okay to merge this now. Cheers :)

**Comment by zencubic** [comment]
@keeferrourke I hadn't committedthe new icon yet. I wanted to hear your opinion first and so i wanted to commit the new icon not until you say it's ok. I created a new pull request for the new icon

**Comment by keeferrourke** [comment]
Right, sorry. Been pretty busy and tired lately. Thanks for this.

**Comment by JackHack96** [comment]
This is so cool!

**Pull request merged**
