### PR TITLE
if lsb_release fail

### PR DESCRIPTION
**Pull request by Manu-sh**
if you need to explain or have questions please ask

### CODE REVIEW

**Comment by keeferrourke** [comment]
@Manu-sh thanks for the patches; I'm gonna need to review these this weekend before I merge the changes. On first glance though, I'm not a fan of your arbitrarily branding everything after Arch Linux by default... If you're running Arch Linux, the config script will brand your system appropriately.

I want this icon pack to be distro agnostic -- hence the GNOME defaults for now. A more generic default will be added in the future.

**Comment by keeferrourke** [comment]
If you could change the default icons back to the way were before, that would be fantastic :+1:

**Comment by Manu-sh** [comment]
yes, im sorry when i have test configure icon are changed by script, after try to reset as default

**Comment by Manu-sh** [comment]
okay so now i close the pull request, when it is ready i send another  pull request

**Pull request closed without merging**
