### PR TITLE
Update Sublime Text logo icon

### PR DESCRIPTION
**Pull request by sptndc**
### Description

Replace with a latest logo of Sublime Text.

|   Icon name   |   Old Icon   |   New Icon   |
| :--------------- | --------------- | --------------- |
| `sublime.svg` |old| new|

### CODE REVIEW

**Comment by keeferrourke** [comment]
You have a lot of unrelated symlinks in this PR that don't make sense. Please remove them.

**Comment by stefano-b** [comment]
Could it make sense to improve the icon by slightly rotating the "S" shape, to align it with the black shape border?

**Comment by sptndc** [comment]
I don't think the icon fits like that, I just try to adjust the icon with the repository name.

**Comment by keeferrourke** [comment]
The design looks good! I just don't want all these unrelated symlinks in this PR.

**Pull request closed without merging**
