### PR TITLE
improved method and distro recognition system extended

### PR DESCRIPTION
**Pull request by Manu-sh**
now seem ready, but if you want to check is a good idea

### CODE REVIEW

**Comment by keeferrourke** [comment]
You absolutely _*cannot*_ remove the copyright header from the configuration script. What made you think you could do that? That is really bad.

You've also taken was should be a series of simple case checks and prompts and over complicated it to an unnecessary degree.

At this point, unless you give me serious reason not to, and actually explain your thought processes, this isn't getting merged.

**Comment by Manu-sh** [comment]
but you can add the copyright as it was before, if the code is difficult to understand the first time it is still much easier to maintain

**Comment by Manu-sh** [comment]
however if you prefer the first pull request (obviously adjusting symbolic links and a forgotten break) no problem you can tell me and i send my orginal pull request (after revision)

**Comment by keeferrourke** [comment]
I'll acknowledge that you've addressed a few deficiencies of my existing script, however they are trivial changes that would've been better reported in the issue tracker. 

Furthermore, this code does not need much maintenance; it's a single script that redoes the symlinking for a few icons in this project. While you've proven you're adept at writing functions in Bash, they aren't useful because the code doesn't need to be reused later in the script - it's called only once. By introducing functions and poorly named variables you make the code *less readable.* 

I'm not satisfied with what's been contributed here as of right now.

**Comment by keeferrourke** [comment]
@Manu-sh the first pull request was much better, without rewriting the entire script, the improvements made sense.

Just make sure you aren't branding my icon theme with Arch Linux logos by default.

**Comment by Manu-sh** [comment]
I just wanted to help and support the project

**Pull request closed without merging**
