### PR TITLE
text editors icons

### PR DESCRIPTION
**Pull request by stefano-b**
### Description

Modified icons for some coding text editors, to make them consistent with the look of the existing icon for Sublime text and other basic text editors.

Included icons:

atom-beta.svg
atom.svg
brackets.svg
code.svg

### CODE REVIEW

**Comment by stefano-b** [comment]
I'm having some problems with `svgcleaner`, it gives a black background to the icon instead of keeping the transparent one: 

https://i.imgur.com/FHHKwma.png

(in this example, atom.svg was processed)

Do you have clue about this? I modified the icon with Inkscape in the first place.

**Comment by keeferrourke** [comment]
Hm, I'm not sure. Maybe just `tidy` on the files, and I can try to play with them later to shrink them with svgcleaner?

**Comment by stefano-b** [comment]
I did some more tests, it happens only with some icons that I edited, and not with others. Probably some kind of corruption at a non-visible level, I don't know.

I'll try to rebuild from skratch the broken ones, and see if it works.

**Comment by stefano-b** [comment]
Redesigned the icons, now I've been able to clean them up as you requested without any kind of problem.

Some minor graphic changes for brackets and code.

**Pull request merged**
