### PR TITLE
if lsb_release fail

### PR DESCRIPTION
**Pull request by Manu-sh**

### CODE REVIEW

**Comment by keeferrourke** [comment]
I just noticed that your modifications ensure that capitals get removed from the distribution name. Glad I moved this to testing; I'm going to make some modifications to your script before I move it to master. Thanks for the help.

**Comment by Manu-sh** [comment]
Yes, i have use ${1,,} (for remove uppercase) because you have use  
DISTRO=$(awk '{print tolower($0)}' <<< $DISTRO) 
and this have same effect:
root@lfs[06:16:51]~}=echo "Try"|awk '{print tolower($0)}' 
try

**Comment by keeferrourke** [comment]
@Manu-sh yeah, I didn't realise that `${1,,}` made everything lower case. This being said, I prefer the awk solution because it's clearer what it does, and it's a reasonable assumption that every system has `awk` in some form or another.

**Comment by Manu-sh** [comment]
you can also use:
tolower=${1,,}

**Comment by keeferrourke** [comment]
thanks, but I'll stick with invoking awk unless you can give me a valid reason not to

**Comment by Manu-sh** [comment]
It would be much better because there are fewer calls

**Comment by Manu-sh** [comment]
root@lfs[06:30:08]~}=time echo ${var,,}
try

real	0m0.000s
user	0m0.000s
sys	0m0.000s
root@lfs[06:30:20]~}=time echo "${var}"|awk '{print tolower($0)}'
try

real	0m0.005s
user	0m0.003s
sys	0m0.001s
root@lfs[06:30:51]~}=

**Comment by keeferrourke** [comment]
I'm just going to prove a point here. You realise that you're optimising against maybe a few *thousandths* of a second right?

    % var=VARIABLE_STRING

    % time echo $var | awk '{print tolower($0)}'
    variable_string

    real    0m0.002s
    user    0m0.000s
    sys     0m0.000s

My system reports 'real' time as 2 milliseconds; in the grand scheme of things, you can completely disregard this. Especially since this is code is meant for a config script that gets run once every time the icon theme is updated.


What you're seeing is likely a deficiency with the time reporting, not `awk`. `awk` *is actually more efficient than `bash`*. Run this test on a novel for instance: [Alice in Wonderland](http://www.gutenberg.org/cache/epub/11/pg11.txt).


    % var=(cat ~/Downloads/pg11.txt)

    % time echo "{$var,,}"
    ...
    real    0m0.062s
    user    0m0.036s
    sys     0m0.004s

    % time echo "$var" | awk '{print tolower($0)}'
    ...
    real    0m0.021s
    user    0m0.016s
    sys     0m0.000s


I'll stick with awk with is more efficient **and** easier to understand at first glace :wink:

**Comment by Manu-sh** [comment]
Also I would use awk to process a text file because awk is faster in processing texts, but if not it's file but small fragments of text easily containable on a single variable called the interpreter to another (in this case, awk) It makes the process slower.

yes I know they are milliseconds, but you asked me a good reason :smile:

**Comment by keeferrourke** [comment]
@Manu-sh fair enough &ndash; I'm honestly just not a fan of bash and it's unintuitive syntax :wink:

**Comment by Manu-sh** [comment]
I'm glad to have helped :smile:

**Pull request merged**
