### PR TITLE
Project Qbittorrent 

### PR DESCRIPTION
**Pull request by now-im**
The first commit redesigns the icon. addresses #345.

### CODE REVIEW

**Comment by keeferrourke** [comment]
This doesn't follow the design trend of other Bittorrent clients that already exist. You should have the bittorrent "wave" etched into the icon. See [transmission](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/transmission.svg) for an example of this.

**Comment by now-im** [comment]
Some of them were .png files. I did what I could. The last commit has been pushed.

**Comment by Riotism** [comment]
I'm not a fan of adding "qb" onto the app icon. What's the idea behind the change?

**Comment by now-im** [comment]
This is the icon that comes close to the latest qbittorrent icon. 
https://github.com/qbittorrent/qBittorrent/pull/6484

**Comment by keeferrourke** [comment]
In this case, updating the design of the existing QBittorent icon doesn't really add any value to the project. La Capitaine playfully reimagines a lot of icons, and replaces bad design choices with informative designs. A "qb" doesn't signifiy bittorrent IMHO.

**Comment by keeferrourke** [comment]
Everything else on this looks fantastic though :)

**Comment by now-im** [comment]
see if this works.

**Comment by Riotism** [comment]
The new icon looks great. Just some to-dos before merging:
- [ ] The icon should be positioned at the center (2px margins on all sides. Right now, it's 1.935px).
- [ ] The border should be colored in the gradient described in the design guidelines.
- [ ] Use linear gradient instead of radial gradient.

**Comment by now-im** [comment]
give me update.

**Comment by keeferrourke** [comment]
I'd give this the go-ahead, but I'll let @Riotism have the final word here.

**Comment by Riotism** [comment]
@now-im I have changed the radial gradient to linear gradient and reduced the size a bit. If you approve of these changes, please comment here and I'll merge it.

**Comment by now-im** [comment]
You don't need to ask for this kind of minor changes. I am just learning. Only major changes should need discussion. Thanks.

**Pull request merged**
