### PR TITLE
Improving Video 4 linux icon

### PR DESCRIPTION
**Pull request by now-im**
The last icon was not very good.

### CODE REVIEW

**Comment by now-im** [comment]
@Riotism for some reason in my system the icon is like this:
image
What is the solution to this problem?

**Comment by Riotism** [comment]
Same issue with the Geogebra icon (#312). Clipping using non-rectangles is not supported by qt. Here the shadow and a black circle is clipped using the blue background. Not supporting clipping using a circle made the black circle and the shadow bleed out.

**Comment by Riotism** [comment]
The solution is to actually crop the shadow so that the border covers it "physically". You need to release the clip in Inkscape (Object > Clip > Release) to see the black circle to delete it.

**Comment by now-im** [comment]
just awesome. Thanks a lot.

**Pull request merged**
