### PR TITLE
Adding Kid3 icon

### LINKED ISSUE #74: [Request] Kid3 icon
Application: Kid3
Icon name: kid3
Context: Applications
Icon reference:

### PR DESCRIPTION
**Pull request by now-im**
fixes #74

### CODE REVIEW

**Comment by keeferrourke** [comment]
This icon's gradient is too light, and is hard to see. I think a symlink to [audio-tag-tool.svg](https://github.com/keeferrourke/la-capitaine-icon-theme/blob/master/apps/scalable/audio-tag-tool.svg) is more appropriate to resolve #74.

**Comment by now-im** [comment]
See the last commit.

**Comment by Riotism** [comment]
Hi, this needs the following changes:
- [ ] The circle with its border needs to be 44x44.
- [ ] The border should be 2px in stroke width.
- [ ] Change the gradient direction so that the lighter color is on the top left.
- [ ] Change the border to follow the design guidelines (under section "Colours").
- [ ] The design might be too complicated. I played with the icon and somehow merged the tag and the note (shown below). Try to find a way so that there's only one element.

kid3 svg


Thanks!

**Comment by now-im** [comment]
I think your icon is perfect, push that instead. I haven't read the color part yet. I will do that later today.

**Comment by now-im** [comment]
I believe I have nailed it.

**Comment by Riotism** [comment]
There are still changes to be made. Please refer to the checklist above.

**Comment by now-im** [comment]
Pushed some change. For some reason, KDE preview is showing weird thing after the change. Please review @Riotism .

**Pull request closed without merging**
