### PR TITLE
add new icons for plasma 5 desktop

### PR DESCRIPTION
**Pull request by somniumAeternam**
This is the first pull request only for the new icons, which I added for the plasma 5 desktop. These icons are mainly taken from your icon theme, antü icon theme and parts of breeze icon theme. I have only adapted the new icons, not created new ones.

### CODE REVIEW

**Comment by keeferrourke** [comment]
You're attempting to push an old README among other things. Please update your local copy of La Capitaine and only commit changes to the individual files you intended to add or modify.

**Comment by somniumAeternam** [comment]
I'm not quite sure, why this is invalid. I forked the repo a couple of minutes before I added the files and made the pull request. I think this is because your testing repo is behind master and my pull request pulls all the changes you made to the master repo. So the readme file is exactly the file in the current master.

**Comment by keeferrourke** [comment]
@somniumAeternam my mistake sorry, I wasn't thinking properly when I reviewed this initially. You are absolutely correct. I'll pull this in when I have a moment and am thinking *clearly*.

Thanks for contributing :)

**Comment by keeferrourke** [comment]
Hey @somniumAeternam, I'm home now, relaxing, thinking clearly. Pulled and merged your branch locally, but I'm going to make a number of changes to the icons you've added if that's alright. As much as I like Antu and Breeze, there are some design decisions I don't agree with. I'm gonna grab some food, then play around with it for a bit and push back into testing.

**Comment by somniumAeternam** [comment]
Sure, play with it as much as you like. I've just added the missing icons for plasma 5 desktop, so that you know, which are missing. And for me the current state is working, which means there are no blank spots in my ui. Of course, these icons don't fit the icon theme perfectly ;)

I will pull the modified icons as well, when I find some time.

**Pull request merged**
